name: humble-package
on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build-package:
    runs-on: ubuntu-latest

    env:
      PACKAGE_NAME: wasm_publisher

    steps:
      - name: Create ROS 2 workspace
        shell: bash -eux {0}
        run: mkdir -p ros-workspace/src

      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ros-workspace/src/$PACKAGE_NAME

      # Runs action and builds package
      - name: Cross-compile package
        uses: ihuicatl/ros2wasm-builder@0.1.1
        with:
          package: $PACKAGE_NAME
          ros_distro: 'humble'
          debug_mode: false
